modid = "hexways"
book = "hexcasting:thehexbook"

resource_dirs = [  # top takes priority
    "resources",
    "{$_project.src}/main/resources",
    { path="{$_project.src}/generated/resources", required=false },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hexways/_export/generated"

[template]
# TODO: change this to point to your actual mod icon
icon = "icon.png"
include = [
    "hexways",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Hexways"
author = "ShadowCube264"
show_landing_text = false

[extra.hexcasting]
# regexes for parsing pattern registry files - if some or all of your patterns aren't being detected by hexdoc, this may need to be updated
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='make\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*(?:new )?(?:ActionRegistryEntry|OperationAction)\(\s*HexPattern\.fromAngles\(\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)\)' }

[[extra.hexcasting.pattern_stubs]]
path = "{$_project.src}/main/java/com/mindlesstoys/stickia/hexways/casting/PatternRegistry.java"
regex = "{^_pattern_regex}"

# source paths

[_project]
src = "../src"
